// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NAN.GitBackupper.Api.Database;

#nullable disable

namespace NAN.GitBackupper.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428140911_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("NAN.GitBackupper.Api.Database.AppRuntimeStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSchedulerRunning")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppRuntimeState", (string)null);
                });

            modelBuilder.Entity("NAN.GitBackupper.Api.Database.BackupProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupIntervalType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupProgressLogDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupRepositoryKeysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupRootPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CachedRepositoriesFetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedRepositoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CleanBackupDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiskUsageLimitPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitLabBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("KeepArchivesUntilDiskLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastBackupDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastBackupSelectedTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastBackupZipArchiveBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderUserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryBackupParallelism")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepositoryBackupSelectionMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryBackupSizesBytesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryBranchesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowOnlySelectedRepositories")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UseAllRepositories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZipAfterBackup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZipArchivesToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZipCompression")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
