<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>NAN.Git</RootNamespace>
    <AssemblyName>NAN.Git</AssemblyName>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NAN.Git.Abstractions\NAN.Git.Abstractions.csproj" />
    <ProjectReference Include="..\NAN.GitBackupper.BitbucketProvider\NAN.GitBackupper.BitbucketProvider.csproj" />
    <ProjectReference Include="..\NAN.GitBackupper.GitHubProvider\NAN.GitBackupper.GitHubProvider.csproj" />
    <ProjectReference Include="..\NAN.GitBackupper.GitLabProvider\NAN.GitBackupper.GitLabProvider.csproj" />
  </ItemGroup>

</Project>
