<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>NAN.Git</RootNamespace>
    <AssemblyName>NAN.Git.Abstractions</AssemblyName>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

</Project>
